packageExtensions:
  '@apollo/react-testing@*':
    dependencies:
      apollo-cache: '*'
      apollo-link: '*'
      '@apollo/client': '*'
      apollo-client: '*'
      apollo-cache-inmemory: '*'
      '@types/react': '*'
      apollo-utilities: '*'
    peerDependencies:
      graphql: '*'
  '@apollo/gateway@*':
    dependencies:
      node-fetch: '*'
  '@atls/react-locale@*':
    dependencies:
      '@types/react': '*'
  '@apollo/react-hooks@*':
    dependencies:
      apollo-cache: '*'
      apollo-link: '*'
      apollo-cache-inmemory: '*'
      graphql: '*'
      react: '*'
      '@types/react': '*'
      '@types/zen-observable': '*'
  '@atls/nestjs-dataloader@*':
    dependencies:
      '@nestjs/core': '*'
    peerDependencies:
      graphql: '*'
  '@atls/next-document-with-helmet@*':
    dependencies:
      react: '*'
      react-helmet: '*'
      next: '*'
      '@types/react': '*'
  '@atls/next-document-with-emotion@*':
    dependencies:
      react: '*'
      emotion-server: '*'
      next: '*'
      '@types/react': '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      '@apollo/react-common': '*'
      '@apollo/react-ssr': '*'
      '@types/react': '*'
      next: '*'
      react: '*'
      zen-observable: '*'
      '@types/zen-observable': '*'
  '@atls/next-app-with-user@*':
    dependencies:
      '@types/react': '*'
  '@atls/next-app-with-provider@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atls/next-app-with-intl@*':
    dependencies:
      '@types/react': '*'
  '@atls/next-app-with-helmet@*':
    dependencies:
      react: '*'
      react-helmet: '*'
      '@types/react': '*'
  '@atls/next-app-with-emotion@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atls/next-app-with-auth@*':
    dependencies:
      '@types/react': '*'
  '@apollo/client@*':
    dependencies:
      react: '*'
      'react-dom': '*'
  '@apollo/react-ssr@*':
    dependencies:
      react: '*'
    peerDependencies:
      graphql: '*'
  '@apollo/link-error@*':
    peerDependencies:
      graphql: '*'
  '@monstrs/nestjs-bus@*':
    dependencies:
      '@monstrs/nestjs-logger': '*'
      '@nestjs/core': '*'
      reflect-metadata: '*'
      serialize-error: '*'
  '@monstrs/nestjs-dataloader@*':
    dependencies:
      '@nestjs/core': '*'
  '@monstrs/server-scripts@*':
    dependencies:
      cross-spawn: '*'
      '@lerna/project': '*'
      serialize-error: '*'
  emotion-server@*:
    dependencies:
      emotion: '*'
  glob-promise@*:
    dependencies:
      glob: '*'
  '@nestjs/common@*':
    dependencies:
      rxjs: '*'
      reflect-metadata: '*'
      cache-manager: '*'
      class-validator: '*'
      class-transformer: '*'
      '@types/node': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      '@nestjs/platform-socket.io': '*'
      reflect-metadata: '*'
      rxjs: '*'
      apollo-server-fastify: '*'
      iterall: '*'
    peerDependencies:
      graphql: '*'
  '@nestjs/graphql@*':
    dependencies:
      '@apollo/subgraph': '*'
      '@apollo/federation': '*'
      '@apollo/gateway': '*'
      '@nestjs/common': '*'
      class-transformer: '*'
      class-validator: '*'
      apollo-server-core: '*'
      apollo-server-express: '*'
      apollo-server-fastify: '*'
      reflect-metadata: '*'
      iterall: '*'
      ts-morph: '*'
    peerDependencies:
      graphql: '*'
      '@nestjs/core': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      '@nestjs/common': '*'
      '@nestjs/websockets': '*'
      '@types/node': '*'
      amqplib: '*'
      amqp-connection-manager: '*'
      kafkajs: '*'
      nats: '*'
      mqtt: '*'
      rxjs: '*'
      redis: '*'
      reflect-metadata: '*'
  '@nestjs/websockets@*':
    dependencies:
      rxjs: '*'
      '@nestjs/platform-socket.io': '*'
  '@nestjs/platform-socket.io@*':
    peerDependencies:
      '@nestjs/core': '*'
  '@nestjs/terminus@*':
    dependencies:
      axios: '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
    peerDependencies:
      '@nestjs/core': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/core': '*'
      '@nestjs/common': '*'
  '@nestjs/mapped-types@*':
    dependencies:
      class-transformer: '*'
  '@node-ts/bus-core@*':
    dependencies:
      '@node-ts/logger-core': '*'
      inversify: '*'
  '@node-ts/ddd@*':
    dependencies:
      '@node-ts/logger-core': '*'
      '@node-ts/bus-core': '*'
      inversify: '*'
      tslib: '*'
  '@node-ts/logger-core@*':
    dependencies:
      tslib: '*'
      inversify: '*'
  '@oryd/hydra-client@*':
    dependencies:
      '@types/node': '*'
  '@grpc/proto-loader@*':
    dependencies:
      '@types/node': '*'
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  '@graphql-typed-document-node/core@*':
    peerDependencies:
      graphql: '*'
  '@mapbox/node-pre-gyp@*':
    dependencies:
      aws-sdk: '*'
      mock-aws-s3: '*'
      nock: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  '@types/rc-trigger@*':
    dependencies:
      'react': '*'
      '@types/react': '*'
  '@emotion/styled@*':
    dependencies:
      '@types/react': '*'
  argon2@*:
    dependencies:
      '@types/node': '*'
  apollo-server-core@*:
    dependencies:
      '@types/node': '*'
    peerDependencies:
      graphql: '*'
  apollo-env@*:
    dependencies:
      '@types/node': '*'
  component-classes@*:
    dependencies:
      indexof: '*'
  graphql-query-complexity@*:
    dependencies:
      graphql: '*'
  graphql-subscriptions@*:
    dependencies:
      '@types/node': '*'
  type-graphql@*:
    dependencies:
      class-validator: '*'
    peerDependencies:
      graphql: '*'
  '@elastic/elasticsearch@*':
    dependencies:
      '@types/node': '*'
  subscriptions-transport-ws@*:
    dependencies:
      '@types/node': '*'
  form-data@*:
    dependencies:
      '@types/node': '*'
  create-emotion-server@*:
    dependencies:
      '@types/node': '*'
  create-react-class@*:
    dependencies:
      react: '*'
  mini-store@*:
    dependencies:
      react: '*'
  next@*:
    dependencies:
      '@types/node': '*'
      react-dom: '*'
  mqtt@*:
    dependencies:
      duplexify: '*'
  rc-align@*:
    dependencies:
      react: '*'
      react-dom: '*'
  rc-collapse@*:
    dependencies:
      react: '*'
      react-dom: '*'
  rc-select@*:
    dependencies:
      react: '*'
      react-dom: '*'
      '@types/react': '*'
  rc-trigger@*:
    dependencies:
      react: '*'
      react-dom: '*'
      '@types/react': '*'
  rc-util@*:
    dependencies:
      react: '*'
      react-dom: '*'
      '@types/react': '*'
  react-scrolllock@*:
    dependencies:
      '@types/react': '*'
  react-dev-utils@*:
    dependencies:
      webpack: '*'
      typescript: '*'
  graphql-tag@*:
    peerDependencies:
      graphql: '*'
  webpack@*:
    dependencies:
      '@types/node': '*'
  '@testing-library/react@*':
    dependencies:
      react-dom: '*'
  next-fonts@*:
    dependencies:
      webpack: '*'
  next-images@*:
    dependencies:
      webpack: '*'
  merge-graphql-schemas@*:
    dependencies:
      graphql-tag-pluck: '*'
  pretty-format@*:
    dependencies:
      '@types/pretty-format': '*'
  debug@*:
    dependencies:
      supports-color: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  apollo-server-errors@*:
    peerDependencies:
      graphql: '*'
  apollo-server-express@*:
    dependencies:
      express: '*'
  graphql-tools@*:
    peerDependencies:
      graphql: '*'
  graphql-toolkit@*:
    peerDependencies:
      graphql: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'
  typescript@*:
    dependencies:
      source-map-support: '*'
  chokidar@*:
    dependencies:
      fsevents: '*'
  ts-morph@*:
    dependencies:
      source-map-support: '*'
  typeorm@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      sqlite3: '*'
  promise-inflight@*:
    dependencies:
      bluebird: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  pg-cursor@*:
    dependencies:
      pg: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220112.hash-947ede7.cjs
