name: Publish image

on:
  workflow_dispatch:

jobs:
  publish:
    uses: atls/shared/.github/workflows/pack-image.yaml@master
    permissions: write-all
    with:
      registryURL: 'ghcr.io'
      registryUser: ${{ github.repository_owner }}
      project: ${{ github.repository_owner }}
      nodeVersion: '22'
    secrets:
      registryKey: ${{ secrets.GITHUB_TOKEN }}
